### PR TITLE
Add modulemd-merge tests

### PR DESCRIPTION
**Pull request by fivaldi**

### CODE REVIEW

**Comment by fivaldi** [comment]
This one should go after #30, #31... then this one as last.

**Comment by FrostyX** [comment]
Thank you for the PR @fivaldi,
I merged PR #30 first, and there are some merge conflicts now.

**Comment by FrostyX** [comment]
I merged PR #31, so once we fix the conflicts here, I can merge as well.

**Comment by FrostyX** [comment]
Some test is failing, please see 
https://copr.fedorainfracloud.org/coprs/frostyx/modulemd-tools/build/1973524/

**Comment by fivaldi** [comment]
@FrostyX Thanks, I also found this when testing locally. Should be fixed now...

**Comment by FrostyX** [comment]
Awesome, thank you.

**Pull request merged**
