### PR TITLE
createrepo: replace deprecated LooseVersion

### PR DESCRIPTION
**Pull request by mkulik-rh**
Warnings in pytest:

```
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12.
```

### CODE REVIEW

**Comment by FrostyX** [comment]
Thank you for the PR @mkulik-rh,
the change looks good and I would very much like to merge it but we ship `modulemd-tools` in RHEL 8.5 and it looks like there is no `python3-packaging` there. I am afraid we will have to choose a different solution.

Or possibly importing it within try-catch?

**Comment by FrostyX** [comment]
Thank you for the PR @mkulik-rh,
the change looks good and I would very much like to merge it but we ship `modulemd-tools` in RHEL 8.5 and it looks like there is no `python3-packaging` there. I am afraid we will have to choose a different solution.

Or possibly importing it within try-catch?

**Comment by mkulik-rh** [comment]
@FrostyX  Completely forgot about RHEL, now it should be covered.

**Comment by FrostyX** [comment]
LGTM, thank you.
We have some failing tests for EPEL-8 but it was not caused by this PR so there is no reason to block it.

**Pull request merged**
