### PR TITLE
Add createrepo_mod tests

### PR DESCRIPTION
**Pull request by fivaldi**

### CODE REVIEW

**Comment by fivaldi** [comment]
Just a note: I'd recommend #30 to be reviewed & merged first

**Comment by FrostyX** [comment]
Thank you for the PR @fivaldi,
I merged PR #30 first, and there are some merge conflicts now.

**Comment by fivaldi** [comment]
@FrostyX Thanks for merging previous PRs. This one should be ready now.

**Comment by FrostyX** [comment]
LGTM and the tests are passing in all chroots, merging.
Thank you @fivaldi.

**Pull request merged**
